# Generated by Django 2.2.4 on 2019-08-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals_catalog', '0002_auto_20190806_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='crystal_habit',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
