# Generated by Django 2.2.4 on 2019-08-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals_catalog', '0003_auto_20190806_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='group',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
