# Generated by Django 2.2.4 on 2019-08-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals_catalog', '0004_mineral_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='group_slug',
            field=models.SlugField(default=2, unique=True),
            preserve_default=False,
        ),
    ]
