# Generated by Django 2.2.4 on 2019-08-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minerals_catalog', '0005_mineral_group_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mineral',
            name='group_slug',
        ),
    ]
